name: ef-grass
channels:
  - conda-forge
dependencies:
  - argcomplete
  - bzip2
  - cairo
  - gdal
  - geos
  - ipython
  - matplotlib
  - netcdf4
  - pandas
  - pillow
  - proj
  - python=3.12
  - scikit-image
  - wxpython
  - zlib
  - zstd